// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jaatxviechhptafgsidx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImphYXR4dmllY2hocHRhZmdzaWR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2OTUzMDksImV4cCI6MjA2MTI3MTMwOX0.Lo2OmgxteA0m3F3qDW5B3Kxjk5j2zv6r3SS7H6gNkbk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);